// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/innotechdevops/rbacman/internal/pkg/response"
	"github.com/innotechdevops/rbacman/internal/rbacman/api/permission"
	"github.com/innotechdevops/rbacman/internal/rbacman/api/role"
	"github.com/innotechdevops/rbacman/internal/rbacman/database"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

func CreateAPI(dbDriver database.Drivers) API {
	dataSource := role.NewDataSource(dbDriver)
	repository := role.NewRepository(dataSource)
	useCase := role.NewUseCase(repository)
	fibererrorResponse := response.New()
	handler := role.NewHandler(useCase, fibererrorResponse)
	validate := role.NewValidate()
	router := role.NewRouter(handler, validate)
	permissionDataSource := permission.NewDataSource(dbDriver)
	permissionRepository := permission.NewRepository(permissionDataSource)
	permissionUseCase := permission.NewUseCase(permissionRepository)
	permissionHandler := permission.NewHandler(permissionUseCase, fibererrorResponse)
	permissionValidate := permission.NewValidate()
	permissionRouter := permission.NewRouter(permissionHandler, permissionValidate)
	apiRouters := NewRouters(router, permissionRouter)
	apiAPI := NewAPI(apiRouters)
	return apiAPI
}
