// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package database

// Injectors from wire.go:

func NewDatabaseDriver() Drivers {
	mongoDriver := NewMongoDbDriver()
	mariaDBDriver := NewMariaDbDriver()
	databaseDrivers := NewDrivers(mongoDriver, mariaDBDriver)
	return databaseDrivers
}
